Revert "[bazel] Disable broken GPU test (#43548)" (#43686)
For some reason if you create 2 InferenceSessions things can fail with:

```
error: 'mo.graph' op requested 2 CUDA devices but only 1 are available
```

Even though the request is actually for the same cuda device twice. This
works around this.

MSDK-645

This reverts commit d3e61a3534e74d62a49f1e7929a54ac5ce14ba10.

MAX_INTEGRATION_TESTS_REV_ID: 0078853c5ae0bd1b911f6aa63578fb4b3f43e3c6