[Kernels] Support 0-sized inputs in `matmul_allreduce`
Overlap scheduling broke multi-gpu llama due to 0-sized inputs in
`matmul_allreduce`.

This resulted in:
```
Unhandled exception caught during execution: At oss/modular/mojo/stdlib/std/gpu/host/nvidia/tma.mojo:400:13: CUDA call failed: CUDA_ERROR_INVALID_VALUE (invalid argument)
```

```
ValueError: At max/kernels/src/linalg/matmul/gpu/__init__.mojo:1098:65: DeviceContext.enqueue_function: Dim value grid_dim.y must be a positive number.
```

The revert is here: [Internal link]

The reason we have 0-sized inputs is because with Overlap scheduling, we
have to run the pipeline even when there are no inputs and get the async
outputs of the last batch.

This parallels to the logic for deepseek where we need to support empty
batches.

MODULAR_ORIG_COMMIT_REV_ID: 43d7fb3b90466fa0f35aae3e9e34bc77da9a9134