[Benchmarking] Add jinja2 requirement to benchmark_serving
Fixes:
```
ubuntu@workspace-bez-purple-manatee-82-h100-2-5dfd87799d-dtwcl:~/modular$ br //max/python/max/benchmark:benchmark_serving -- --model meta-llama/Llama-3.1-8B-Instruct --dataset-name sonnet --sonnet-input-len 40000 --output-lengths 100 --print-inputs-and-outputs
INFO: Invocation ID: 8214da09-3d55-4789-86da-272cc20f5c71
INFO: Streaming build results to: https://modular.buildbuddy.io/invocation/8214da09-3d55-4789-86da-272cc20f5c71
INFO: Analyzed target //max/python/max/benchmark:benchmark_serving (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //max/python/max/benchmark:benchmark_serving up-to-date:
  bazel-bin/max/python/max/benchmark/benchmark_serving
Aspect //bazel/pip:mypy.bzl%mypy_aspect of //max/python/max/benchmark:benchmark_serving up-to-date:
  bazel-bin/max/python/max/benchmark/benchmark_serving.mypy_stdout
INFO: Elapsed time: 0.465s, Critical Path: 0.02s
INFO: 1 process: 1 action cache hit, 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Streaming build results to: https://modular.buildbuddy.io/invocation/8214da09-3d55-4789-86da-272cc20f5c71
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
19:46:56.167 INFO: benchmark_serving: Namespace(arxiv_summarization_input_len=15000, backend='modular', base_url=None, batch_job_image_dir=None, burstiness=1.0, chat_warmup_delay_ms=0.0, collect_cpu_stats=True, collect_gpu_stats=False, collect_server_stats=True, config_file=None, dataset_mode=<DatasetMode.HUGGINGFACE: 'huggingface'>, dataset_name='sonnet', dataset_path=None, delay_between_chat_turns=None, disable_tqdm=False, endpoint='/v1/chat/completions', host='localhost', ignore_first_turn_stats=False, lora=None, lora_paths=[], lora_uniform_traffic_ratio=0.0, max_benchmark_duration_s=None, max_concurrency=None, max_concurrent_lora_ops=1, max_output_len=None, metadata=[], model='meta-llama/Llama-3.1-8B-Instruct', model_max_length=None, num_chat_sessions=None, num_prompts=1000, obfuscated_conversations_average_output_len=175, obfuscated_conversations_coefficient_of_variation=0.1, obfuscated_conversations_shuffle=False, output_lengths='100', per_lora_traffic_ratio=[], port=8000, print_inputs_and_outputs=True, random_coefficient_of_variation='0.3,0.7', random_distribution_type='normal', random_first_turn_ratio=1.0, random_image_count=0, random_image_size='', random_input_len=1024, random_max_num_unique_sys_prompt=1, random_num_turns=1, random_output_len=128, random_sys_prompt_ratio=0.0, record_output_lengths=None, request_rate='inf', result_filename=None, seed=0, skip_first_n_requests=0, skip_test_prompt=False, sonnet_input_len=40000, sonnet_prefix_len=200, temperature=0.0, tokenizer=None, top_k=None, top_p=1.0, trace=False, trace_file=None, trace_session=None, trust_remote_code=False)
19:46:56.168 INFO: benchmark_serving: getting tokenizer. api url: http://localhost:8000/v1/chat/completions
19:46:56.828 INFO: benchmark_serving: sampling requests
Traceback (most recent call last):
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/python/max/benchmark/benchmark_serving.runfiles/_main/max/python/max/benchmark/benchmark_serving.py", line 1816, in <module>
    main(args)
    ~~~~^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/python/max/benchmark/benchmark_serving.runfiles/_main/max/python/max/benchmark/benchmark_serving.py", line 1506, in main
    input_requests = benchmark_dataset.sample_requests(
        num_requests=args.num_prompts,
    ...<4 lines>...
        apply_chat_template=apply_chat_template,
    )
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/python/max/benchmark/benchmark_serving.runfiles/_main/max/python/max/benchmark/benchmark_shared/datasets/sonnet.py", line 94, in sample_requests
    base_prompt_formatted = tokenizer.apply_chat_template(
        base_message, add_generation_prompt=True, tokenize=False
    )
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/python/max/benchmark/benchmark_serving.runfiles/rules_pycross++lock_file+modular_pip_lock_file_repo/deps/transformers@4.57.1/site-packages/transformers/tokenization_utils_base.py", line 1666, in apply_chat_template
    rendered_chat, generation_indices = render_jinja_template(
                                        ~~~~~~~~~~~~~~~~~~~~~^
        conversations=conversations,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        **template_kwargs,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/python/max/benchmark/benchmark_serving.runfiles/rules_pycross++lock_file+modular_pip_lock_file_repo/deps/transformers@4.57.1/site-packages/transformers/utils/chat_template_utils.py", line 482, in render_jinja_template
    compiled_template = _compile_jinja_template(chat_template)
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/a8246705211370f9a29d0c6e94adcf5a/execroot/_main/bazel-out/k8-dbg/bin/max/python/max/benchmark/benchmark_serving.runfiles/rules_pycross++lock_file+modular_pip_lock_file_repo/deps/transformers@4.57.1/site-packages/transformers/utils/chat_template_utils.py", line 395, in _compile_jinja_template
    raise ImportError(
        "apply_chat_template requires jinja2 to be installed. Please install it using `pip install jinja2`."
    )
ImportError: apply_chat_template requires jinja2 to be installed. Please install it using `pip install jinja2`.
```
MODULAR_ORIG_COMMIT_REV_ID: 0971f387ba9884deb0ccd6c1d551d5f2e1c8ac87