[MAX] Use 24MB as the default shared memory threshold for ZMQ serialization, Try 2
In a benchmark, I was seeing a bunch of calls to `open_shm_array_file`
even though the input lengths were super small (eg: 500 tokens).

I believe that KyleC had previously profiled this and determined 24MB to
be a reasonable threshold to enable shared memory serialization.

Add assertion message for shared memory check to prevent pytest from
printing 10s of MB to stdout

Remove test for default value. This is because the default value of 24MB
is bigger than what is available on m7i ci runners.

---

The first attempt was reverted by Thomas
[Internal link]

The failure was due to:
```
% br smoke-test allenai/olmOCR-2-7B-1025-FP8
File "block_utils.py", line 68, in hash_request_tokens
token_ids[idx] = img.image_hash
~~~~~~~~~^^^^^
ValueError: assignment destination is read-only
```

The fix involves moving the call to `TokenBuffer._ensure_writeable` from
`__init__` to `__post_init__`. This ensures that the token array is
always
writable even if this token buffer was created via deserialization.

MODULAR_ORIG_COMMIT_REV_ID: 4336e883667401648d7fd24ac1d4665387c810ea