[max][pipelines] Set deadline=None for causal attention tests (#48285)
This should address the issue reported in
[Internal link]

```
FAILED SDK/integration-test/pipelines/python/llama3/test_causal_attention_mask.py::test_causal_mask__does_not_mask_prior_tokens - hypothesis.errors.FlakyFailure: Hypothesis test_causal_mask__does_not_mask_prior_tokens(start_pos=[395,
 501,
 496,
 233,
 71,
 297,
 126,
 431,
 303,
 141,
 47,
 340,
 511,
 328,
 263,
 511,
 328,
 109,
 306,
 444,
 268,
 138,
 182,
 415,
 151,
 324,
 441,
     444,
     268,
     138,
     182,
     415,
     151,
     324,
     441,
     469,
     1],
    seq_len=[216,
     18,
     288,
     51,
     406,
     326,
     219,
     217,
     153,
     441,
     465,
     151,
     421,
     199,
     498,
     84,
     441,
     84,
     505,
     311,
     250,
     114,
     439,
     156,
     40,
     320,
     481,
     172,
     279],
)
Unreliable test timings! On an initial run, this test took 278.12ms, which exceeded the deadline of 200.00ms, but on a subsequent run it took 119.89 ms, which did not. If you expect this sort of variability in your test timings, consider turning deadlines off for this test by setting deadline=None.
```

MAX_INTEGRATION_TESTS_REV_ID: 353e769c93992e28e2a01f5bb4e5458d32a4da29