[Overlap] Fix preemption + overlap scheduler bug by deleting future token when context is reset
When a preemption occurs when using overlap scheduler, MAX Serve crashes
in the subsequent iteration.

For example:
```
Requesting API:  51%|█████     | 674/1319 [04:05<02:01,  5.31it/s]01:00:23.055 INFO: Executed TG batch with 64 reqs | Terminated: 0 reqs, Pending: 0 reqs | Input Tokens: 64/128 toks | Context Tokens: 91369/10880 toks | Prompt Tput: 1.5K tok/s, Generation Tput: 1.5K tok/s | Batch creation: 474.32us, Execution: 42.34ms | KVCache usage: 51.3% of 680 blocks, Cache hit rate: 0.0% | All Preemptions: 0 reqs

Requesting API:  51%|█████     | 675/1319 [04:05<03:02,  3.53it/s]01:00:24.328 INFO: Preempted a request due to lack of KV pages. This can affect the end-to-end performance. Consider increasing device-memory-utilization via `--device-memory-utilization` to provide more KV cache memory. Total Preemption Count: 1
...
  File "/home/runner/.cache/bazel/_bazel_runner/e5185c6d580a8eeb67820192d4a9baf7/execroot/_main/bazel-out/k8-opt-ci-build/bin/max/tests/integration/accuracy/pipelines-lm-eval.runfiles/_main/max/python/max/profiler/tracing.py", line 111, in wrapper
    return func(*args, **kwargs)
  File "/home/runner/.cache/bazel/_bazel_runner/e5185c6d580a8eeb67820192d4a9baf7/execroot/_main/bazel-out/k8-opt-ci-build/bin/max/tests/integration/accuracy/pipelines-lm-eval.runfiles/_main/max/python/max/pipelines/lib/pipeline_variants/overlap_text_generation.py", line 810, in execute
    context.update_with_future_token()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/runner/.cache/bazel/_bazel_runner/e5185c6d580a8eeb67820192d4a9baf7/execroot/_main/bazel-out/k8-opt-ci-build/bin/max/tests/integration/accuracy/pipelines-lm-eval.runfiles/_main/max/python/max/pipelines/core/context.py", line 315, in update_with_future_token
    raise ValueError("Cannot have multiple future tokens.")
ValueError: Cannot have multiple future tokens.
```

This is what happens:
```
iteration 1: [100, 101, ..., 116] (generated_length = 0)
iteration 2: [100, 101, ..., 116, FUTURE_TOKEN] (generated_length = 1)
iteration 3: [100, 101, ..., 116, 117, FUTURE_TOKEN] (generated_length = 2)
iteration 4: [100, 101, ..., 116, 117, 118, FUTURE_TOKEN] (generated_length = 0)

**PREEMPT!!!**

iteration 5: [100, 101, ..., 116, 117, 118, 119, FUTURE_TOKEN, FUTURE_TOKEN] (generated_length = 1)
                                                     ^^^^ Cannot have multiple future tokens.
```

Notice that we have this logic:
```
\\ If generated_length is still 0, then there is no placeholder
\\ future token. This is possible due to chunked prefill.
if context.tokens.generated_length:
    context.realize_future_token(
        new_token=next_token, log_probabilities=log_probs
    )
```

So when a preemption occurs, the `generated_length` is reset to 0. Thus
the `context.realize_future_token` is not run after the preemption. This
causes us to have multiple future tokens in a row.

There are two options to fix this:
1. When a preemption occurs, keep the future token. Then realize the
future
token in the next iteration even if `generated_length` is 0. This means
     that we will not lose the progress from that iteration.
2. When a preemption occurs, delete the future token. This means that we
will
     lose the progress from that iteration.

I picked #2. This loses an iteration of progress when a preemption
occurs
relative to option #1. However, it is simpler. This is because the
placeholder
future token would become part of the prompt in #1 despite the future
token
still needing to be associated with log_probs and still needing to be
streamed
to the user in `consume_recently_generated_tokens`.

MODULAR_ORIG_COMMIT_REV_ID: 0a21e63721148e2c2c85f9037f0d68b27eaeb405