[Max] Add check for rope_interleave attribute (#72832)
Related to MAXSERV-1047, CLIN-595

The HF config has had the `rope_interleave` attribute removed for this
model, causing `--trust-remote-code` to fail with:
```
AttributeError: 'DeepseekV3Config' object has no attribute 'rope_interleave'
```

Added a check to ensure that attribute is available, otherwise default
to `True`

MODULAR_ORIG_COMMIT_REV_ID: c095f2441de5451bc119d3bdcef852071be740db